# Generated by Django 6.1 on 2026-09-13 01:05

import django.db.models.deletion
import django.db.models.functions.text
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('ipam', '0097_merge_ipaddress_host_index_and_multi_protocol_services'),
        ('netbox_access_relations', '0001_initial'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('is_co_located', models.BooleanField(db_index=True, default=False, editable=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_relation_system_addresses', to='ipam.ipaddress')),
                ('ip_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_relation_system_addresses', to='ipam.iprange')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_relation_system_addresses', to='ipam.prefix')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='netbox_access_relations.applicationsystem')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('system', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='applicationsystem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='accessrel_appsystem_name_ci_unique', violation_error_message='An application system with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='systemaddress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ip_address__isnull', True), ('ip_range__isnull', True), ('prefix__isnull', False)), models.Q(('ip_address__isnull', False), ('ip_range__isnull', True), ('prefix__isnull', True)), models.Q(('ip_address__isnull', True), ('ip_range__isnull', False), ('prefix__isnull', True)), _connector='OR'), name='accessrel_systemaddress_exactly_one_target', violation_error_message='Select exactly one Prefix, IP address, or IP range.'),
        ),
        migrations.AddConstraint(
            model_name='systemaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('prefix__isnull', False)), fields=('system', 'prefix'), name='accessrel_systemaddress_system_prefix_unique'),
        ),
        migrations.AddConstraint(
            model_name='systemaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('system', 'ip_address'), name='accessrel_systemaddress_system_ip_unique'),
        ),
        migrations.AddConstraint(
            model_name='systemaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_range__isnull', False)), fields=('system', 'ip_range'), name='accessrel_systemaddress_system_range_unique'),
        ),
    ]
