# Generated by Django 6.1 on 2026-09-15

import django.db.models.deletion
import django.db.models.functions.text
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0144_customfield_status"),
        ("netbox_access_relations", "0004_systemalias"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner")),
                ("source_system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="outbound_access_policies", to="netbox_access_relations.applicationsystem")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                ("target_system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inbound_access_policies", to="netbox_access_relations.applicationsystem")),
            ],
            options={"verbose_name": "Access policy", "verbose_name_plural": "Access policies", "ordering": ("name", "pk")},
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PolicyService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("protocol", models.CharField(max_length=3)),
                ("is_any", models.BooleanField(default=False)),
                ("port_start", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("port_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="services", to="netbox_access_relations.accesspolicy")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={"verbose_name": "Policy service", "verbose_name_plural": "Policy services", "ordering": ("policy", "protocol", "is_any", "port_start", "port_end", "pk")},
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(model_name="accesspolicy", constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), name="accessrel_accesspolicy_name_ci_unique", violation_error_message="An access policy with this name already exists.")),
        migrations.AddConstraint(model_name="accesspolicy", constraint=models.CheckConstraint(condition=models.Q(("source_system", models.F("target_system")), _negated=True), name="accessrel_accesspolicy_distinct_systems", violation_error_message="Source and target systems must be different.")),
        migrations.AddConstraint(model_name="accesspolicy", constraint=models.CheckConstraint(condition=models.Q(("valid_from__isnull", True), ("valid_until__isnull", True), ("valid_until__gt", models.F("valid_from")), _connector="OR"), name="accessrel_accesspolicy_valid_period", violation_error_message="Valid until must be later than valid from.")),
        migrations.AddConstraint(model_name="policyservice", constraint=models.CheckConstraint(condition=models.Q(models.Q(("is_any", True), ("port_end__isnull", True), ("port_start__isnull", True)), models.Q(("is_any", False), ("port_end__lte", 65535), ("port_start__gte", 1), ("port_start__lte", models.F("port_end"))), _connector="OR"), name="accessrel_policyservice_valid_ports", violation_error_message="Use ANY or a port range between 1 and 65535.")),
        migrations.AddConstraint(model_name="policyservice", constraint=models.UniqueConstraint(condition=models.Q(("is_any", True)), fields=("policy", "protocol"), name="accessrel_policyservice_unique_any")),
        migrations.AddConstraint(model_name="policyservice", constraint=models.UniqueConstraint(condition=models.Q(("is_any", False)), fields=("policy", "protocol", "port_start", "port_end"), name="accessrel_policyservice_unique_range")),
    ]
